import imageA from '../../img/words/a.png'
import imageB from '../../img/words/b.png'
import imageC from '../../img/words/c.png'
import imageD from '../../img/words/d.png'
import imageE from '../../img/words/e.png'
import imageF from '../../img/words/f.png'
import imageG from '../../img/words/g.png'
import imageH from '../../img/words/h.png'
import imageI from '../../img/words/i.png'
import imageJ from '../../img/words/j.png'
import imageK from '../../img/words/k.png'
import imageL from '../../img/words/l.png'
import imageM from '../../img/words/m.png'
import imageN from '../../img/words/n.png'
import imageO from '../../img/words/o.png'
import imageP from '../../img/words/p.png'

export default () => [imageA, imageB, imageC, imageD, imageE, imageF, imageG, imageH, imageI, imageJ, imageK, imageL, imageM, imageN, imageO, imageP];
