import image1 from '../../img/numbers/1_p1_.png'
import image11 from '../../img/numbers/a_p1_.png'
import image2 from '../../img/numbers/2_p2_.png'
import image12 from '../../img/numbers/12_p2_.png'
import image3 from '../../img/numbers/3_p3_.png'
import image13 from '../../img/numbers/13_p3_.png'
import image4 from '../../img/numbers/4_p4_.png'
import image14 from '../../img/numbers/14_p4_.png'
import image5 from '../../img/numbers/5_p5_.png'
import image15 from '../../img/numbers/15_p5_.png'
import image6 from '../../img/numbers/6_p6_.png'
import image16 from '../../img/numbers/16_p6_.png'
import image7 from '../../img/numbers/7_p7_.png'
import image17 from '../../img/numbers/17_p7_.png'
import image8 from '../../img/numbers/8_p8_.png'
import image18 from '../../img/numbers/18_p8_.png'
import image9 from '../../img/numbers/9_p9_.png'
import image19 from '../../img/numbers/19_p9_.png'
import image10 from '../../img/numbers/10_p10_.png'
import image20 from '../../img/numbers/20_p10_.png'


export default () => [image1, image11, image2, image12, image3, image13, image4, image14, image5, image15, image6, image16, image7, image17, image8, image18, image9, image19, image10, image20];
