import imageA from '../images-game/words/a.png'
import imageB from '../images-game/words/b.png'
import imageC from '../images-game/words/c.png'
import imageD from '../images-game/words/d.png'
import imageE from '../images-game/words/e.png'
import imageF from '../images-game/words/f.png'
import imageG from '../images-game/words/g.png'
import imageH from '../images-game/words/h.png'
import imageI from '../images-game/words/i.png'
import imageJ from '../images-game/words/j.png'
import imageK from '../images-game/words/k.png'
import imageL from '../images-game/words/l.png'
import imageM from '../images-game/words/m.png'
import imageN from '../images-game/words/n.png'
import imageO from '../images-game/words/o.png'
import imageP from '../images-game/words/p.png'

export default () => [imageA, imageB, imageC, imageD, imageE, imageF, imageG, imageH, imageI, imageJ, imageK, imageL, imageM, imageN, imageO, imageP];
